config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  get 'messages/destroy'
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'recruit_login' => 'sessions#recruit_login' # かんたんログインページ https://cat-pia.com/recruit_login/
  get 'rank' => 'shops#rank' # ランキング機能
  get 'mapindex' => 'shops#mapindex' # 地図一覧表示機能
  get 'random' => 'shops#random' # ランダム表示機能
  get 'introduce' => 'shops#introduce'
  post 'login' => 'sessions#create'
  post '/static_pages/guest_sign_in' => 'static_pages#new_guest'
  delete 'logout' => 'sessions#destroy'
  resources :users do  # フォロー機能について追記
    member do
      get :following, :followers
    end
  end
  # collection...全体のデータにアクセスする際に使用 resources以外のアクション
  resources :shops # IDがあるかないかで決定される
  resources :relationships, only: [:create, :destroy] # create・destroyアクションのルーティング追記
  get :favorites, to: 'favorites#index' # お気に入り一覧表示アクション
  post   "favorites/:shop_id/create"  => "favorites#create" # shop_idを入れ、お気に入り登録の識別をする
  delete "favorites/:shop_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy] # Commentsコントローラ・create・destroyアクション追記
  resources :notifications, only: :index # Notificationsコントローラ追記
  resources :messages, only: [:create, :destroy] # Messagesコントローラ追記
  resources :rooms, :only => [:create, :show, :index] # Roomsコントローラ追記
end

app/models/shop.rb
class Shop < ApplicationRecord #コールバック call back・・・例として登録後の確認メール
  belongs_to :user
  has_many :favorites, dependent: :destroy # お気に入り機能実装により追記
  has_many :comments, dependent: :destroy # コメント機能実装による追記
  has_many :favorited_users, through: :favorites, source: :user # いいねランキング実装により追記
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 30 }
  validates :description, length: { maximum: 150 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :recommended_points, length: { maximum: 50 }
  validates :rating,
            :numericality => {
              :only_interger => true,
              :greater_than_or_equal_to => 1,
              :less_than_or_equal_to => 5
            },
            allow_nil: true
  validate :picture_size
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  acts_as_taggable

  # ねこカフェ投稿に附するコメントのフィードを作成 #
  def feed_comment(shop_id)
    Comment.where("shop_id = ?", shop_id)
  end

  private

    # アップロード画像の容量を制限する
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, ":5MBより大きい画像はアップロードできません。")
      end
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :logged_in_user # ログインユーザーのみ投稿可能
  before_action :correct_user, only: [:edit, :update] # 投稿した本人のみがedit,updateを行える

  # ねこカフェ投稿アクション
  def new
    @shop = Shop.new
  end

  def create
    @shop = current_user.shops.build(shop_params)
    if @shop.save
      flash[:success] = "投稿が完了しました！"
      redirect_to shop_path(@shop) # 投稿後、投稿詳細画面へ遷移
    else
      render 'shops/new'
    end
  end

  # 猫カフェ検索後・タグ絞り込み
  def index
    #@favorites_count = Favorite.where(shop_id: params[:shop_id]).count
    if params[:tag_name]
      @shops = Shop.tagged_with(params[:tag_name]).page(params[:page])
    end
    @tags = Shop.tag_counts_on(:tags)
  end

  def search
  end

  def rank
    #@all_ranks = Shop.find(Favorit e.group(:shop_id).order('count(shop_id) desc').limit(3).pluck(:shop_id))
    @all_ranks = Shop.all.sort {|a,b| b.favorited_users.count <=> a.favorited_users.count}
  end

  # ねこカフェ投稿詳細ページへ
  def show
    @shop = Shop.find(params[:id])
    @comment = Comment.new # コメント機能
    @hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow shop.name
    end
    #@favorites_count = Favorite.where(shop_id: params[:shop_id]).count
  end

  # ねこカフェ投稿編集処理
  def edit
    @shop = Shop.find(params[:id])
  end

  # ねこカフェ投稿更新処理
  def update
    @shop = Shop.find(params[:id])
    if @shop.update_attributes(shop_params)
      flash[:success] = "ねこカフェ情報が更新されました！"
      redirect_to @shop # 更新後、詳細ページへ遷移
    else
      render 'edit' # 更新できなかった場合は編集画面を表示
    end
  end

  # ねこカフェ投稿削除処理
  def destroy
    @shop = Shop.find(params[:id])
    if current_user.admin? || current_user?(@shop.user)
      @shop.destroy
      flash[:success] = "投稿が削除されました！"
      redirect_to request.referrer == user_url(@shop.user) ? user_url(@shop.user) : root_url
    else
      flash[:danger] = "他人の投稿は削除できません！"
      redirect_to root_url
    end
  end

  def mapindex
    @shops = Shop.all
    @hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow shop.name
    end
  end

  def random
    @random = Shop.order("RAND()").all
  end

  def tags
    @tags = Shop.includes(:taggings).tag_counts_on(:tags)
  end

  private

    # 登録できる項目をshop_paramsメソッドで定義する
    def shop_params
      params.require(:shop).permit(:name, :description, :address, :recommended_points, :web_page, :rating, :picture, :latitude, :longitude, :tag_list)
    end

    # 現在のユーザーが更新対象のねこカフェ投稿を保有しているかどうか確認する
    def correct_user
      @shop = current_user.shops.find_by(id: params[:id])
      redirect_to root_url if @shop.nil?
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_icon.html.slim
.allcat
  = link_to image_tag("allcat.png", class:"allcat_top"), root_path
.ranking_top
  = link_to image_tag("ranking.png", class:"ranking_top"), rank_path
.newpost_top
  = link_to image_tag("newpost.png", class:"newpost_top"), new_shop_path
.maps_top
  = link_to image_tag("maps.png", class:"maps_top"), mapindex_path
.today_top
  = link_to image_tag("today.png", class:"today_top"), random_path
.member_top
  = link_to image_tag("member.png", class:"member_top"), users_path

app/views/shops/_shop.html.slim
- @shop = shop
/- @favorites_count = Favorite.where(shop_id: params[:shop_id]).count
- @favorites_count = Favorite.where(shop_id: @shop.id).count
ul
  p
  .container
    .row
      h6.shop.html.slim.text-center
        .col-xs-12
          .card.shadow[style="height: 600px; width: 335px"]
            .col-md-12.text-center
              p
              h5.name-shop
                = link_to shop.name, shop_path(shop)
              h8.user-name
                |　Posted by：
                = link_to shop.user.name, user_path(shop.user)
              p
              li
              .shop-image.text-center
                = link_to((image_tag shop.picture.thumb400.url), shop_path(shop.id), class: 'shop-picture') if shop.picture.url.present?
              .fukidasi
                = shop.description
              p
              br
              li.feed_shops
              .favorite-form
                = render 'users/favorite_form'
                /= @favorites_count
              p
              .comment-new.fa
                = link_to shop_path(shop, anchor: "form")
                  .far.fa-comment-alt.fa-lg
              li
                .detail-shop
                  = link_to "もっと見る", shop_path(shop)

              = render 'shops/tag_list', tag_list: shop.tag_list
              p

              .change-shop
              - if current_user.admin? || (current_user == shop.user)
                = link_to "編集", edit_shop_path(shop)
                |　|　
                = link_to "削除", shop_path(shop), method: :delete, class: 'del_dis',
                                data: { confirm: "本当に削除しますか？" }
              p
              .timestamp.text-right
                = time_ago_in_words(shop.created_at)
                | 前に投稿
              p
              br
            p

app/views/shops/_shop_form.html.slim
  .container
    .card.card-body.bg-light.col-md-7.mx-auto
      = form_with model: @shop, local: true do |f|
        = render 'shared/error_messages', object: f.object
        .form-group
          span.picture
          =  f.label :picture
          | 　
          span.input-unneed
            | 　任意
          = f.file_field :picture, accept: 'image/jpeg,image/png', class: 'form-control', id: 'shop_picture'
        .form-group
          = f.label :name, '店名'
          |
          span.input-need
            |　※必須
          = f.text_field :name, class: 'form-control', id: 'shop_name'
        .form-group
          = f.label :description
          |　
          span.input-unneed
            | 任意
          = f.text_field :description, size: "60x4", class: 'form-control', id: 'shop_description'
        .form-group
          = f.label :address
          |  (都道府県名から入力)
          span.input-need
            | 　※必須
          = f.text_field :address, class: 'form-control', id: 'shop_address'
        .form-group
          = f.label :recommended_points
          |
          span.input-unneed
            | 　任意
          = f.text_field :recommended_points, size: "30x4", class: 'form-control', id: 'shop_recommended_points'
        .form-group
          = f.label :web_page
          |
          span.input-unneed
            | 　任意
          = f.text_field :web_page, class: 'form-control', id: 'shop_web_page'
        .form-group
          = f.label :rating
          |  [1~5]
          span.input-unneed
            |　 任意
          = f.text_field :rating, class: 'form-control', id: 'rating'
        .form-group
          = f.label :tag_list
          span.input-unneed
            |　任意　※半角スペースで複数のタグ付けが可能です
          = f.text_field :tag_list, value: @shop.tag_list.join(","), class: "form-control"
        br
          = f.submit nil, class: 'btn btn-info'

      javascript:
        $('#shop_picture').bind('change', function() {
          var size_in_megabytes = this.files[0].size/1024/1024;
          if (size_in_megabytes > 5) {
            alert('アップロードできる写真の最大サイズは5MBです。5MB以下の画像を選択してください');
          }
        });

app/views/shops/_tag_list.html.slim
- tag_list.each do |tag|
  span.badge.badge-info.mr-1.p-2
    = link_to tag, shops_path(tag_name: tag), class: "text-white"

app/views/shops/edit.html.slim
- provide(:title, "猫カフェ情報の編集")
.container
  .row
    .card-body.col-md-8
      = form_for(@shop) do |f|
        = render 'shared/error_messages', object: f.object
        span.picture
        = f.label :picture
        | 　
        span.input-unneed
          | ※任意
        = f.file_field :picture, accept: 'image/jpg,image/png', class: 'form-control', id: 'shop-picture'
        = link_to((image_tag @shop.picture.thumb400.url), shop_path(@shop.id), class: 'shop-picture') if @shop.picture.url.present?
        p
        br
        h3
          | 猫カフェ情報の編集
        p
        .form-group
          = f.label :name
          |　
          span.input-need
            | ※必須
          = f.text_field :name, class: 'form-control', id: 'shop_name'
        .form-group
          = f.label :description
          |　
          span.input-unneed
            | 任意
          = f.text_field :description, class: 'form-control', id: 'shop_description'
        .form-group
          = f.label :address
          |
          span.input-need
            |　※必須　(都道府県から入力)
          = f.text_field :address, class: 'form-control', id: 'shop_address'
        .form-group
          = f.label :recommended_points
          |
          span.input-unneed
            | 　任意
          = f.text_field :recommended_points, class: 'form-control', id: 'shop_recommended_points'
        .form-group
          = f.label :web_page
          |
          span.input-unneed
            | 　任意
          = f.text_field :web_page, class: 'form-control', id: 'shop_web_page'
        .form-group
          = f.label :rating
          |  [1~5]
          span.input-unneed
            |　 任意
          = f.text_field :rating, class: 'form-control', id: 'rating'
        .form-group
          = f.label :tag_list
          span.input-unneed
            |　※ 半角スペースで複数のタグ付けが可能です
          = f.text_field :tag_list, value: @shop.tag_list.join(" "), class: "form-control"

        = f.submit "更新する", class: "btn btn-info"
        /.del_dis
        = link_to "投稿を削除", shop_path(@shop), method: :delete, class: "del_dis",
                              data: { confirm: "本当に削除してよろしいですか？"}

app/views/shops/index.html.slim
- provide(:title, '猫カフェ投稿一覧')
.container
  - if params[:q].present? && params[:q][:name_or_address_cont].present?
    h3.text-center
      | ”
      = params[:q][:name_or_address_cont]
      | ”の検索結果：
      = @shops.count
      | 件
    p
  - else
    h3.text-center
      | 絞り込み結果
    /- @tags.each do |tag|
      = link_to tag, shops_path(:action => :tag, :tag => tag.name)
    p
  .container
    ol.shops
      .row
        h5.col-xs-12
          /card.shadow
          .d-flex.flex-row
            .row
              = render @shops

app/views/shops/introduce.html.slim
#app
  ul#tabMenu
    .container-int.text-center
      li v-bind:class=("{'active': active === 1}") v-on:click="change(1)" みんなの猫カフェ
      li v-bind:class=("{'active': active === 2}") v-on:click="change(2)" 人気の猫カフェ
      li v-bind:class=("{'active': active === 3}") v-on:click="change(3)" 今日の猫カフェ
      p
      p v-if=("active === 1")
        = render 'shared/feed'
      p v-else-if=("active === 2")
      p v-else-if=("active === 3")  今日の猫カフェ


script src="https://cdn.jsdelivr.net/npm/vue"

javascript:
    new Vue({
    el: '#app',
    data: {
      active: 1
    },
    methods: {
      change: function(num) {
        this.active = num;
      }
    }
  })

app/views/shops/mapindex.html.slim
#map.gmap-mapindex
div id='map2' style='height: 800px; width: 100%;'

= javascript_include_tag src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyAh_mxXXCr5aAy-KrOHfg_q3SZsxNiwHPg&callback=initMap", async: true, defer: true

javascript:
  var map;
  var marker = [];
  var infoWindow = [];
  var markerData = [ // マーカーを立てる場所名・緯度・経度
    {
          name: 'てまりのおうち',
          lat: 35.705170,
          lng: 139.577048,
  }, {
          name: 'miagolare',
          lat: 35.697623,
          lng: 139.671462,

          name: '要にゃんこ亭',
          lat: 35.734815,
          lng: 139.700470,
  }, {
          name: 'いやし亭 ほご猫茶屋',
          lat: 35.694788,
          lng: 139.696402
  }, {
          name: '保護猫カフェ ヘミングウェイ',
          lat: 35.169221,
          lng: 136.940240,
  }, {
          name: 'ひとやすみ',
          lat: 35.173258,
          lng: 136.902393,
  }, {
          name: '猫カフェ なーごなーご',
          lat: 35.193976,
          lng: 137.068631,
  }
  ];

  function initMap() {
  // 地図の作成
      var mapLatLng = new google.maps.LatLng({lat: markerData[0]['lat'], lng: markerData[0]['lng']}); // 緯度経度のデータ作成
    map = new google.maps.Map(document.getElementById('map2'), { // #sampleに地図を埋め込む
      center: mapLatLng, // 地図の中心を指定
        zoom: 8 // 地図のズームを指定
    });

  // マーカー毎の処理
  for (var i = 0; i < markerData.length; i++) {
          markerLatLng = new google.maps.LatLng({lat: markerData[i]['lat'], lng: markerData[i]['lng']}); // 緯度経度のデータ作成
          marker[i] = new google.maps.Marker({ // マーカーの追加
          position: markerLatLng, // マーカーを立てる位置を指定
              map: map // マーカーを立てる地図を指定
        });

      infoWindow[i] = new google.maps.InfoWindow({ // 吹き出しの追加
          content: '<div class="sample">' + markerData[i]['name'] + '</div>' // 吹き出しに表示する内容
        });

      markerEvent(i); // マーカーにクリックイベントを追加
  }

    marker[0].setOptions({// TAM 東京のマーカーのオプション設定
          icon: {
          url: markerData[0]['icon']// マーカーの画像を変更
        }
    });
  }

  // マーカーにクリックイベントを追加
  function markerEvent(i) {
      marker[i].addListener('click', function() { // マーカーをクリックしたとき
        infoWindow[i].open(map, marker[i]); // 吹き出しの表示
    });
  }

app/views/shops/new.html.slim
- provide(:title, "猫カフェ投稿")
.container
  ol
  h3.text-center
    | 猫カフェ投稿
  br
  .row
    .col-md-6.col-md-offset-3
    = render 'shops/shop_form'

app/views/shops/random.html.slim
.container
  .text-center
    h4.feed-home
      = render 'shops/icon'

.container
  .text-center
    h4.rank-cat
      | 今日の猫カフェ
    br
      | あなたにオススメの今日の猫カフェです
    br
  .row.text-center
    br
    p
    - @random.each.with_index(1) do |shop, i|
      h5.col-md-4.mx-auto
        .card.shadow[style="width: 370px"]
          p
          |　第
          = i
          |位
          |　
          = link_to shop.name, shop_path(shop)
          br
          p
            = link_to((image_tag shop.picture.thumb400.url), shop_path(shop.id), class: 'shop-picture') if shop.picture.url.present?
          p
          .user-name.rank
                |　　　　　　　 　Posted by ：
                = link_to shop.user.name, user_path(shop.user)

app/views/shops/rank.html.slim
/- @all_ranks = Shop.find(Favorite.group(:shop_id).order('count(shop_id) desc').limit(3).pluck(:shop_id))
 - @all_ranks = Shop.all.sort {|a,b| b.favorited_users.count <=> a.favorited_users.count}

.container
  .text-center
    h4.feed-home
      = render 'shops/icon'

.container
  .text-center
    h4.rank-cat
      | 人気の猫カフェ
    br
    p
  .row.text-center
    br
    p
    - @all_ranks.each.with_index(1) do |shop, i|
      h5.col-md-4.mx-auto
        .card.shadow[style="width: 370px"]
          p
          |　第
          = i
          |位
          |　
          = link_to shop.name, shop_path(shop)
          br
          p
            = link_to((image_tag shop.picture.thumb400.url), shop_path(shop.id), class: 'shop-picture') if shop.picture.url.present?
          p
          .user-name.rank
                |　　　　　　　 　Posted by ：
                = link_to shop.user.name, user_path(shop.user)

app/views/shops/show.html.slim
- provide(:title, "#{@shop.name}")
- @comments = @shop.feed_comment(@shop.id)
- shop = Shop.find(params[:id])
- @favorites_count = Favorite.where(shop_id: @shop.id).count

.container
  .text-center
    h4.feed-home
      = render 'shops/icon'

.container.shop.html.slim
  .col-md-8.mx-auto
    h4.name-shop-show
      = link_to shop.name, shop_path(shop)
    h8.user-name
      |　Posted by :
      = link_to shop.user.name, user_path(shop.user)
    p

    .card.card-body.col-lg-20.text-left
      .shop-image.text-center
        = link_to((image_tag shop.picture.thumb400.url), shop_path(shop.id), class: 'shop-picture') if shop.picture.url.present?
      .shop-favorite-form
        = render 'users/favorite_form'
      .show.comment-new.fa.fa-lg
        = link_to "\uf27a", { anchor: "form" }
      p
      .shop-address-show
        |  所在地：
        = shop.address
      p
      .shop-web_page
        | WEB：
        = link_to "#{@shop.web_page}", @shop.web_page, target: "_blank"
      br
      .shop-description
        | 店舗説明：
        = shop.description
      p
      br
      .shop-title-recommended_points
        | おすすめポイント：
        = shop.recommended_points
      p
      br
      ul.shop-rating
        | おすすめ度：
        - if @shop.rating.present?
          = "⭐️" * shop.rating
          = "☆" * (5 - shop.rating)
      p
        = render 'shops/tag_list', tag_list: shop.tag_list

      br
        //管理者ユーザーまたは投稿作成ユーザー以外には削除を表示させない
      .change-shop-show
        - if current_user.admin? || (current_user == shop.user)
          = link_to "編集", edit_shop_path(shop)
          |　|　
          = link_to "削除", shop_path(shop.id), method: :delete, class: 'del_dis',
                          data: { confirm: "本当に削除しますか？" }
      .timestamp.text-right
        = time_ago_in_words(shop.created_at)
        | 前に投稿
      p
    p
    .comment.form-comments
      = render "comments/feed_comments"
    #form
      = render "comments/new"
  p
  .google_map
    | 店舗地図

div id='map' style='height: 500px; width: 100%;'

= javascript_include_tag src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyAh_mxXXCr5aAy-KrOHfg_q3SZsxNiwHPg&callback=initMap", async: true, defer: true

javascript:
  function initMap() {
    var test ={ lat: #{@shop.latitude}, lng: #{@shop.longitude} };
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: test
    });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = "所在地：#{@shop.address} ";
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
      position:test,
      map: map,
      title: contentString
    });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }