config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  get 'messages/destroy'
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'recruit_login' => 'sessions#recruit_login' # かんたんログインページ https://cat-pia.com/recruit_login/
  get 'rank' => 'shops#rank' # ランキング機能
  get 'mapindex' => 'shops#mapindex' # 地図一覧表示機能
  get 'random' => 'shops#random' # ランダム表示機能
  get 'introduce' => 'shops#introduce'
  post 'login' => 'sessions#create'
  post '/static_pages/guest_sign_in' => 'static_pages#new_guest'
  delete 'logout' => 'sessions#destroy'
  resources :users do  # フォロー機能について追記
    member do
      get :following, :followers
    end
  end
  # collection...全体のデータにアクセスする際に使用 resources以外のアクション
  resources :shops # IDがあるかないかで決定される
  resources :relationships, only: [:create, :destroy] # create・destroyアクションのルーティング追記
  get :favorites, to: 'favorites#index' # お気に入り一覧表示アクション
  post   "favorites/:shop_id/create"  => "favorites#create" # shop_idを入れ、お気に入り登録の識別をする
  delete "favorites/:shop_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy] # Commentsコントローラ・create・destroyアクション追記
  resources :notifications, only: :index # Notificationsコントローラ追記
  resources :messages, only: [:create, :destroy] # Messagesコントローラ追記
  resources :rooms, :only => [:create, :show, :index] # Roomsコントローラ追記
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :shop_id, presence: true
  validates :variety, presence: true
  validates :from_user_id, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :logged_in_user

  def index
    @notifications = current_user.notifications
    current_user.update_attribute(:notification, false)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.slim
- user = User.find(notification.from_user_id)
- shop = Shop.find(notification.shop_id)
- id = "notification = notification.id"

- if notification.variety == 1 # お気に入り登録の通知
  p
    = notification.created_at.strftime("%Y/%m/%d(%a) %H:%M")
  .notification-message
  p
    | あなたの猫カフェ投稿が「
    = link_to user.name, user_path(user)
    | 」さんにお気に入り登録されました。

- elsif notification.variety == 2 # コメントの通知
  p
    = notification.created_at.strftime("%Y/%m/%d(%a) %H:%M")
  p.notification-message
    | あなたの猫カフェ投稿に「
    = link_to user.name, user_path(user)
    | 」さんがコメントしました。
    br
    |「
    = notification.content
    | 」
.row
  .col-md-2
    = link_to((image_tag shop.picture.thumb300.url), shop_path(shop), class: 'shop-picture')
  p
  p
  .col-md-7
    p
    br
    h5
      = link_to shop.name, shop_path(shop)
    p
    p
      = shop.description
    li
  p
  br
p

app/views/notifications/index.html.slim
- breadcrumb :notifications
.container
  .row
    .col-md-12
      h4.text-center
        | 通知一覧
  - if @notifications.present?
    .container.card
      .notifications
        = render @notifications